### ISSUE TITLE
Remove banner and add PDF guide

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/bilmehakki-theme#25]
"Hello Gemma,

We have two very quick requests about the website. 

Firstly, we would like to remove the horizontal green window that pops up on the top of the website's front page and which says "Olağanüstü Hal'de Bilgi Edinme Hakkı" (Right to Access Information During State of Emergency) as seen in the screenshot below. The content will also be removed.

We would also like to add a downloadable pdf guidebook for journalists. The document we would like to see on the website is attached. I am not sure whether it can be added to the front page, or it would be better to insert it under the "help" section. The ideal title would be a bit long - "Gazeteciler için Bilgi Edinme Hakkı Kanunu Kılavuzu" - but we can shorten it if necessary.

Kind regards,
Özgün."
[4982.pdf](https://github.com/mysociety/bilmehakki-theme/files/2269516/4982.pdf)

**Comment by garethrees** [comment]
Extracted in to two separate issues so that they can be worked on independently:

* https://github.com/mysociety/bilmehakki-theme/issues/26
* https://github.com/mysociety/bilmehakki-theme/issues/27
